const ENV_CONFIG = {
  BACKEND_PORT: Bun.env.PORT,
  GOOGLE_OAUTH_CLIENT_ID: Bun.env.GOOGLE_OAUTH_CLIENT_ID,
  GOOGLE_OAUTH_CLIENT_SECRET: Bun.env.GOOGLE_OAUTH_CLIENT_SECRET,
  GOOGLE_OAUTH_REDIRECT_URL: Bun.env.GOOGLE_OAUTH_REDIRECT_URL,
}

export default ENV_CONFIG;