const ENV_CONFIG = {
  BACKEND_PORT: Bun.env.PORT,
  GOOGLE_OAUTH_CLIENT_ID: Bun.env.GOOGLE_OAUTH_CLIENT_ID ?? "",
  GOOGLE_OAUTH_CLIENT_SECRET: Bun.env.GOOGLE_OAUTH_CLIENT_SECRET ?? "",
  GOOGLE_OAUTH_REDIRECT_URL: Bun.env.GOOGLE_OAUTH_REDIRECT_URL ?? "",

  // encoding
  ENCRYPTION_SECRET:
    process.env.ENCRYPTION_SECRET ?? "e0e84e4138y2e5creaf2e6d22f33a647",
  IV_HEX_STRING:
    process.env.IV_HEX_STRING ?? "1a583e157cfdf819305f7a7409163c89",

  JWT_SECRET: process.env.JWT_SECRET || "",
  JWT_REFRESH_TOKEN_EXPIRY: process.env.JWT_REFRESH_TOKEN_EXPIRY || "30d",
  JWT_ACCESS_TOKEN_EXPIRY: process.env.JWT_ACCESS_TOKEN_EXPIRY || "7d",
}

export default ENV_CONFIG;